import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/components/SessionProvider"
import { authOptions } from "./api/auth/[...nextauth]/route"
import ReactQueryClientProvider from "@/components/ReactQueryClientProvider";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";

export const metadata = {
  title: process.env.NEXT_PUBLIC_APP_NAME,
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
	const session = await getServerSession(authOptions)

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen antialiased")}>
        <SessionProvider session={session}>
          <ReactQueryClientProvider>
              {children}
          </ReactQueryClientProvider>
        </SessionProvider>
        <Toaster />
      </body>
    </html>
  );
}
